language: python
python:
  - "2.7"
  - "3.6" 
  - "3.7"  
# command to install dependencies
install:
  - pip install -r requirements.txt

  before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/app.py"
  - export FLASK_DEBUG=1
# command to run tests
script:
  - pytest

deploy:
  provider: heroku
  api_key: 768c4a9b-63da-475d-bbc0-0b7f9b0bd60a
  on: dev